import 'package:flutter/material.dart';
import 'dart:async';

import '../SideDrawer.dart';
import 'package:dio/dio.dart';

class CryptoScreen extends StatefulWidget {
  static const route = "/crypto";

  const CryptoScreen({Key key}) : super(key: key);

  @override
  CryptoScreenState createState() => CryptoScreenState();
}

class Autogenerated {
  double uSD;
  Autogenerated({this.uSD});
  Autogenerated.fromJson(Map<String, dynamic> json) {
    uSD = json['USD'];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['USD'] = this.uSD;
    return data;
  }
}

class CryptoScreenState extends State<CryptoScreen> {
  Response response;
  Dio dio = new Dio();
  var btcPrice = "null";
  var ethPrice = "null";
  Timer _timer;

  @override
  void initState() {
    super.initState();
    _timer = Timer.periodic(new Duration(seconds: 1), (timer) async {
      response = await dio.get(
          "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD");
      Autogenerated btcPriceRes = Autogenerated.fromJson(response.data);
      response = await dio.get(
          "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD");
      Autogenerated ethPriceRes = Autogenerated.fromJson(response.data);
      if (mounted) {
        setState(() {
          btcPrice = btcPriceRes.uSD.toString();
          ethPrice = ethPriceRes.uSD.toString();
        });
      } else {
        _timer.cancel();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: SideDrawer(),
      appBar: AppBar(
        title: Text('Dashboard'),
        backgroundColor: Colors.black,
      ),
      body: Center(
          child: Column(children: <Widget>[
        Text("BTC PRICE " + btcPrice + "\$"),
        Text("ETH PRICE " + ethPrice + "\$"),
      ])),
    );
  }
}
