import 'package:flutter/material.dart';
import 'dart:async';

import '../SideDrawer.dart';
import 'package:dio/dio.dart';

class CryptoScreen extends StatefulWidget {
  static const route = "/crypto";

  const CryptoScreen() : super();

  @override
  CryptoScreenState createState() => CryptoScreenState();
}

class Autogenerated {
  double uSD;
  Autogenerated({this.uSD});
  Autogenerated.fromJson(Map<String, dynamic> json) {
    uSD = json['USD'];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['USD'] = this.uSD;
    return data;
  }
}

class CryptoScreenState extends State<CryptoScreen> {
  var btcPrice = "null";
  var ethPrice = "null";

  @override
  void initState() {
    getHttp();
    super.initState();
  }

  void getHttp() async {
    try {
      Response response;
      Dio dio = new Dio();
      Timer.periodic(new Duration(seconds: 2), (timer) async {
        response = await dio.get(
            "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD");
        Autogenerated btcPriceRes = Autogenerated.fromJson(response.data);
        response = await dio.get(
            "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD");
        Autogenerated ethPriceRes = Autogenerated.fromJson(response.data);
        setState(() {
          btcPrice = btcPriceRes.uSD.toString();
          ethPrice = ethPriceRes.uSD.toString();
        });
      });
    } catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: SideDrawer(),
      appBar: AppBar(
        title: Text('Dashboard'),
        backgroundColor: Colors.black,
      ),
      body: Center(
          child: Column(children: <Widget>[
        Text(btcPrice),
        Text(ethPrice),
      ])),
    );
  }
}
